# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c58ca881d001eaf5e090c91c1f72ffd27a31d00cd19c0c92a0211268222489dc673be05df0c41d13f7495450c01d97fba44d318d88625bc1b679c1c1f28900fe

test:
  secret_key_base: c109db45a40d871d94ae46a508f8de418ef19dcc208944d76cfba456a9bc005f661595fb0bc330e29c0885c1d6d885ccb0840fc6372f875471b13e8ee477f29f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
